from models import Base, UserModel, FileModel, ProjectModel
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from os import environ

POSTGRES_URL="127.0.0.1:5432"
POSTGRES_USER="postgres"
POSTGRES_PW="sqladmin"
POSTGRES_DB="test"

DB_URL = 'postgresql+psycopg2://{user}:{pw}@{url}/{db}'.format(user=POSTGRES_USER,pw=POSTGRES_PW,url=POSTGRES_URL,db=POSTGRES_DB)

# Create engine
engine = create_engine(DB_URL, echo=True)

# Create All Tables
Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)

# Create session
Session = sessionmaker(bind=engine)
s = Session()

user1 = UserModel(name='A', email='a@a.com')
user2 = UserModel(name='B', email='b@b.com')
user3 = UserModel(name='C', email='c@c.com')
user4 = UserModel(name='D', email='d@d.com')
user5 = UserModel(name='E', email='e@e.com')
user6 = UserModel(name='F', email='f@f.com')
user7 = UserModel(name='G', email='g@g.com')
user8 = UserModel(name='H', email='h@h.com')
user9 = UserModel(name='I', email='i@i.com')
user10 = UserModel(name='J', email='j@j.com')
user11 = UserModel(name='K', email='k@k.com')
user12 = UserModel(name='L', email='l@l.com')
user13 = UserModel(name='M', email='m@m.com')
user14 = UserModel(name='N', email='n@n.com')
user15 = UserModel(name='O', email='o@o.com')

file1 = FileModel(name='File 1', typename='text')
file2 = FileModel(name='File 2', typename='mp3')
file3 = FileModel(name='File 3', typename='pdf')
file4 = FileModel(name='File 4', typename='text')
file5 = FileModel(name='File 5', typename='mp3')
file6 = FileModel(name='File 6', typename='text')
file7 = FileModel(name='File 7', typename='text')
file8 = FileModel(name='File 8', typename='mp3')
file9 = FileModel(name='File 9', typename='text')
file10 = FileModel(name='File 10', typename='mp3')
file11 = FileModel(name='File 11', typename='pdf')
file12 = FileModel(name='File 12', typename='mp3')
file13 = FileModel(name='File 13', typename='text')
file14 = FileModel(name='File 14', typename='text')
file15 = FileModel(name='File 15', typename='mp3')
file16 = FileModel(name='File 16', typename='text')
file17 = FileModel(name='File 17', typename='mp3')
file18 = FileModel(name='File 18', typename='text')
file19 = FileModel(name='File 19', typename='pdf')
file20 = FileModel(name='File 20', typename='text')
file21 = FileModel(name='File 21', typename='mp3')
file22 = FileModel(name='File 22', typename='text')
file23 = FileModel(name='File 23', typename='mp3')
file24 = FileModel(name='File 24', typename='pdf')
file25 = FileModel(name='File 25', typename='text')
file26 = FileModel(name='File 26', typename='text')
file27 = FileModel(name='File 27', typename='mp3')
file28 = FileModel(name='File 28', typename='pdf')
file29 = FileModel(name='File 29', typename='text')
file30 = FileModel(name='File 30', typename='mp3')

project1 = ProjectModel(name='Project 1', startdate='2020-04-06')
project2 = ProjectModel(name='Project 2', startdate='2020-04-06')
project3 = ProjectModel(name='Project 3', startdate='2020-04-06')
project4 = ProjectModel(name='Project 4', startdate='2020-04-06')
project5 = ProjectModel(name='Project 5', startdate='2020-04-06')
project6 = ProjectModel(name='Project 6', startdate='2020-04-06')
project7 = ProjectModel(name='Project 7', startdate='2020-04-06')
project8 = ProjectModel(name='Project 8', startdate='2020-04-06')
project9 = ProjectModel(name='Project 9', startdate='2020-04-06')
project10 = ProjectModel(name='Project 10', startdate='2020-04-06')
project11 = ProjectModel(name='Project 11', startdate='2020-04-06')
project12 = ProjectModel(name='Project 12', startdate='2020-04-06')
project13 = ProjectModel(name='Project 13', startdate='2020-04-06')
project14 = ProjectModel(name='Project 14', startdate='2020-04-06')
project15 = ProjectModel(name='Project 15', startdate='2020-04-06')

project1.files.append(file1)
project1.files.append(file2)
project1.files.append(file3)
project2.files.append(file4)
project2.files.append(file5)
project3.files.append(file6)
project4.files.append(file7)
project4.files.append(file8)
project5.files.append(file9)
project5.files.append(file10)
project5.files.append(file11)
project6.files.append(file12)
project6.files.append(file13)
project7.files.append(file14)
project8.files.append(file15)
project8.files.append(file16)
project9.files.append(file17)
project10.files.append(file18)
project10.files.append(file19)
project11.files.append(file20)
project11.files.append(file21)
project11.files.append(file22)
project12.files.append(file23)
project12.files.append(file24)
project13.files.append(file25)
project13.files.append(file26)
project14.files.append(file27)
project14.files.append(file28)
project14.files.append(file29)
project15.files.append(file30)

user1.projects.append(project1)
user1.projects.append(project3)
user2.projects.append(project1)
user2.projects.append(project5)
user2.projects.append(project15)
user3.projects.append(project3)
user4.projects.append(project2)
user4.projects.append(project8)
user5.projects.append(project6)
user5.projects.append(project8)
user5.projects.append(project10)
user6.projects.append(project2)
user6.projects.append(project9)
user7.projects.append(project5)
user8.projects.append(project8)
user8.projects.append(project13)
user9.projects.append(project14)
user10.projects.append(project14)
user10.projects.append(project15)
user11.projects.append(project7)
user12.projects.append(project4)
user12.projects.append(project9)
user12.projects.append(project14)
user13.projects.append(project1)
user13.projects.append(project11)
user14.projects.append(project5)
user14.projects.append(project11)
user14.projects.append(project15)
user15.projects.append(project12)

s.add(user1)
s.add(user2)
s.add(user3)
s.add(user4)
s.add(user5)
s.add(user6)
s.add(user7)
s.add(user8)
s.add(user9)
s.add(user10)
s.add(user11)
s.add(user12)
s.add(user13)
s.add(user14)
s.add(user15)

s.commit()
s.close()